//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceWebRole
{
    using System;
    using System.Collections.Generic;
    
    public partial class connection
    {
        public int idconnection { get; set; }
        public Nullable<int> user_iduser { get; set; }
        public Nullable<int> device_iddevice { get; set; }
        public System.DateTime dateConnection { get; set; }
        public string ipv4 { get; set; }
        public string ipv6 { get; set; }
    
        public virtual user user { get; set; }
    }
}
