//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceWebRole
{
    using System;
    using System.Collections.Generic;
    
    public partial class countryResources
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public countryResources()
        {
            this.user = new HashSet<user>();
        }
    
        public int idcountryResources { get; set; }
        public string countryCode { get; set; }
        public string country { get; set; }
        public string validationEmailContent { get; set; }
        public string validationEmailTitle { get; set; }
        public string resetPassordEmailContent { get; set; }
        public string resetPassordEmailTitle { get; set; }
        public string resetPassordRequestEmailContent { get; set; }
        public string resetPassordRequestEmailTitle { get; set; }
        public string alertSOSEmailContent { get; set; }
        public string alertSOSEmailTitle { get; set; }
        public string alertSOSEmailWithMsgContent { get; set; }
        public string alertZoneEmailContent { get; set; }
        public string alertMoveEmailContent { get; set; }
        public string alertZoneEmailTitle { get; set; }
        public string alertMoveEmailTitle { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> user { get; set; }
    }
}
