//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceWebRole
{
    using System;
    using System.Collections.Generic;
    
    public partial class logExceptionSES
    {
        public int idlogException { get; set; }
        public System.DateTime exceptionDate { get; set; }
        public string exceptionMessage { get; set; }
        public string innerException { get; set; }
        public string url { get; set; }
        public string data { get; set; }
        public string method { get; set; }
        public string headers { get; set; }
        public string defaultCustomError { get; set; }
    }
}
