//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceWebRole
{
    using System;
    using System.Collections.Generic;
    
    public partial class logVodafoneAndOnesignal
    {
        public int idLogVodafoneAndOnesignal { get; set; }
        public string minorCode { get; set; }
        public string majorCode { get; set; }
        public string outcome { get; set; }
        public string msgRef { get; set; }
        public string imsi { get; set; }
        public string apiUser { get; set; }
        public System.DateTime dateBegin { get; set; }
        public System.DateTime dateEnd { get; set; }
    }
}
