//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceWebRole
{
    using System;
    using System.Collections.Generic;
    
    public partial class operationFromStore
    {
        public int idoperationFromStore { get; set; }
        public int idPack { get; set; }
        public int idUser { get; set; }
        public string status { get; set; }
        public System.DateTime dateTransaction { get; set; }
        public string refStore { get; set; }
        public string versionApp { get; set; }
        public int creditsPurchased { get; set; }
        public bool isPackPremium { get; set; }
    }
}
