//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceWebRole
{
    using System;
    using System.Collections.Generic;
    
    public partial class packCredit
    {
        public int idcreditPack { get; set; }
        public string price { get; set; }
        public int rewarding { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public int isPromotion { get; set; }
        public string promotion { get; set; }
        public string colorBacground { get; set; }
        public string colorHeaderBackground { get; set; }
        public string language { get; set; }
        public string idProduct { get; set; }
        public int operation_idOperationType { get; set; }
    }
}
