//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceWebRole
{
    using System;
    using System.Collections.Generic;
    
    public partial class seekiosProduction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public seekiosProduction()
        {
            this.location = new HashSet<location>();
            this.seekiosInstruction = new HashSet<seekiosInstruction>();
            this.historyLocation = new HashSet<historyLocation>();
        }
    
        public int idseekiosProduction { get; set; }
        public string imei { get; set; }
        public string uidSeekios { get; set; }
        public string macAddress { get; set; }
        public string imsi { get; set; }
        public Nullable<byte> lastUpdateConfirmed { get; set; }
        public int versionEmbedded_idversionEmbedded { get; set; }
        public Nullable<System.DateTime> dateFirstRegistration { get; set; }
        public int freeCredit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<location> location { get; set; }
        public virtual seekios seekios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<seekiosInstruction> seekiosInstruction { get; set; }
        public virtual versionEmbedded versionEmbedded { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historyLocation> historyLocation { get; set; }
    }
}
