//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceWebRole
{
    using System;
    using System.Collections.Generic;
    
    public partial class seekiosCommunication
    {
        public int idseekiosCommunication { get; set; }
        public int seekiosBatteryLife { get; set; }
        public int seekiosSignalQuality { get; set; }
        public System.DateTime sendDate { get; set; }
        public System.DateTime receptionDate { get; set; }
        public int seekios_idseekios { get; set; }
    }
}
