//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceWebRole
{
    using System;
    using System.Collections.Generic;
    
    public partial class seekiosHardwareReport
    {
        public Nullable<int> SeekiosProdID { get; set; }
        public Nullable<bool> GSMUSART { get; set; }
        public Nullable<bool> GSM_GPRS { get; set; }
        public Nullable<bool> GPSUSART { get; set; }
        public Nullable<bool> GSPFrames { get; set; }
        public Nullable<bool> GPSPosit { get; set; }
        public Nullable<bool> IMUgetaccel { get; set; }
        public Nullable<bool> BLEConfig { get; set; }
        public Nullable<bool> IMUInterrupt { get; set; }
        public Nullable<bool> BLEAdvertizing { get; set; }
        public Nullable<bool> BLEConnection { get; set; }
        public Nullable<bool> DataFlashRead { get; set; }
        public Nullable<bool> DataFlashWrite { get; set; }
        public Nullable<bool> LEDs { get; set; }
        public Nullable<bool> Bouton { get; set; }
        public Nullable<bool> CalendarTime { get; set; }
        public Nullable<bool> CalendarInterrupt { get; set; }
        public Nullable<int> DateDuTest { get; set; }
        public int SeekiosHardwareReportID { get; set; }
        public Nullable<int> CalendarTimestamp { get; set; }
        public Nullable<int> BatteryLife { get; set; }
        public Nullable<bool> AdcUSB { get; set; }
        public Nullable<bool> AdcBattery { get; set; }
    }
}
