//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceWebRole
{
    using System;
    using System.Collections.Generic;
    
    public partial class seekiosAndSeekiosProduction
    {
        public Nullable<int> idseekios { get; set; }
        public string seekiosName { get; set; }
        public byte[] seekiosPicture { get; set; }
        public Nullable<System.DateTime> seekios_dateCretaion { get; set; }
        public Nullable<int> batteryLife { get; set; }
        public Nullable<int> signalQuality { get; set; }
        public Nullable<System.DateTime> dateLastCommunication { get; set; }
        public Nullable<double> lastKnownLocation_longitude { get; set; }
        public Nullable<double> lastKnownLocation_latitude { get; set; }
        public Nullable<double> lastKnownLocation_altitude { get; set; }
        public Nullable<double> lastKnownLocation_accuracy { get; set; }
        public Nullable<System.DateTime> lastKnownLocation_dateLocationCreation { get; set; }
        public Nullable<int> user_iduser { get; set; }
        public Nullable<byte> hasGetLastInstruction { get; set; }
        public Nullable<byte> isAlertLowBattery { get; set; }
        public Nullable<byte> isInPowerSaving { get; set; }
        public Nullable<int> powerSaving_hourStart { get; set; }
        public Nullable<int> powerSaving_hourEnd { get; set; }
        public Nullable<int> alertSOS_idalert { get; set; }
        public Nullable<byte> isRefreshingBattery { get; set; }
        public Nullable<System.DateTime> dateLastOnDemandRequest { get; set; }
        public Nullable<byte> isLastSOSRead { get; set; }
        public Nullable<int> lastKnowLocation_idlocationDefinition { get; set; }
        public Nullable<System.DateTime> dateLastSOSSent { get; set; }
        public Nullable<byte> sendNotificationOnNewTrackingLocation { get; set; }
        public Nullable<byte> sendNotificationOnNewOutOfZoneLocation { get; set; }
        public Nullable<byte> sendNotificationOnNewDontMoveLocation { get; set; }
        public int idseekiosProduction { get; set; }
        public string imei { get; set; }
        public string uidSeekios { get; set; }
        public string macAddress { get; set; }
        public string imsi { get; set; }
        public Nullable<byte> lastUpdateConfirmed { get; set; }
        public int versionEmbedded_idversionEmbedded { get; set; }
        public Nullable<System.DateTime> dateFirstRegistration { get; set; }
        public int freeCredit { get; set; }
    }
}
