//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceWebRole
{
    using System;
    using System.Collections.Generic;
    
    public partial class sharing
    {
        public int user_iduser { get; set; }
        public int friend_iduser { get; set; }
        public int seekios_idseekios { get; set; }
        public System.DateTime dateBeginSharing { get; set; }
        public Nullable<System.DateTime> dateEndSharing { get; set; }
        public byte isUserOwner { get; set; }
    
        public virtual friendship friendship { get; set; }
        public virtual seekios seekios { get; set; }
    }
}
