//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceWebRole
{
    using System;
    using System.Collections.Generic;
    
    public partial class token
    {
        public int idToken { get; set; }
        public int user_iduser { get; set; }
        public string authToken { get; set; }
        public System.DateTime dateCreationToken { get; set; }
        public System.DateTime dateExpiresToken { get; set; }
    
        public virtual user user { get; set; }
    }
}
