//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceWebRole
{
    using System;
    using System.Collections.Generic;
    
    public partial class versionEmbedded
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public versionEmbedded()
        {
            this.seekiosProduction = new HashSet<seekiosProduction>();
        }
    
        public int idVersionEmbedded { get; set; }
        public string versionName { get; set; }
        public System.DateTime dateVersionCreation { get; set; }
        public string releaseNotes { get; set; }
        public string SHA1Hash { get; set; }
        public bool isBetaVersion { get; set; }
        public string releaseNotesEnglish { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<seekiosProduction> seekiosProduction { get; set; }
    }
}
