//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSeekiosUnitTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class device
    {
        public int iddevice { get; set; }
        public string deviceName { get; set; }
        public string os { get; set; }
        public string plateform { get; set; }
        public string macAdress { get; set; }
        public string notificationPlayerId { get; set; }
        public System.DateTime lastUseDate { get; set; }
        public string uidDevice { get; set; }
        public int doNotDisturb { get; set; }
        public string countryCode { get; set; }
        public int user_iduser { get; set; }
    
        public virtual user user { get; set; }
    }
}
