//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSeekiosUnitTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class seekios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public seekios()
        {
            this.location = new HashSet<location>();
            this.mode = new HashSet<mode>();
        }
    
        public int idseekios { get; set; }
        public string seekiosName { get; set; }
        public byte[] seekiosPicture { get; set; }
        public System.DateTime seekios_dateCretaion { get; set; }
        public Nullable<int> batteryLife { get; set; }
        public Nullable<int> signalQuality { get; set; }
        public Nullable<System.DateTime> dateLastCommunication { get; set; }
        public double lastKnownLocation_longitude { get; set; }
        public double lastKnownLocation_latitude { get; set; }
        public Nullable<double> lastKnownLocation_altitude { get; set; }
        public Nullable<double> lastKnownLocation_accuracy { get; set; }
        public Nullable<System.DateTime> lastKnownLocation_dateLocationCreation { get; set; }
        public int user_iduser { get; set; }
        public byte hasGetLastInstruction { get; set; }
        public byte isAlertLowBattery { get; set; }
        public byte isInPowerSaving { get; set; }
        public int powerSaving_hourStart { get; set; }
        public int powerSaving_hourEnd { get; set; }
        public Nullable<int> alertSOS_idalert { get; set; }
        public byte isRefreshingBattery { get; set; }
        public Nullable<System.DateTime> dateLastOnDemandRequest { get; set; }
        public Nullable<byte> isLastSOSRead { get; set; }
        public int lastKnowLocation_idlocationDefinition { get; set; }
        public Nullable<System.DateTime> dateLastSOSSent { get; set; }
    
        public virtual alert alert { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<location> location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mode> mode { get; set; }
        public virtual seekiosProduction seekiosProduction { get; set; }
        public virtual user user { get; set; }
    }
}
