//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceEmbeddedUnitTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class mode
    {
        public int idmode { get; set; }
        public Nullable<System.DateTime> dateModeCreation { get; set; }
        public string trame { get; set; }
        public Nullable<int> countOfTriggeredAlert { get; set; }
        public Nullable<System.DateTime> lastTriggeredAlertDate { get; set; }
        public int seekios_idseekios { get; set; }
        public int modeDefinition_idmodeDefinition { get; set; }
        public int statusDefinition_idstatusDefinition { get; set; }
        public int device_iddevice { get; set; }
    }
}
