//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceEmbeddedUnitTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class seekiosInstruction
    {
        public int idseekiosInstruction { get; set; }
        public string instruction { get; set; }
        public System.DateTime dateCreation { get; set; }
        public int seekiosProduction_idseekiosProduction { get; set; }
        public Nullable<int> instructionType { get; set; }
    }
}
